- hosts: localhost
  gather_facts: false
  collections:
  - ansible.controller
  tasks:
  - set_fact:
      user: "{{ lookup('env', VMWARE_USER) }}"
      host: "{{ lookup('env',VMWARE_HOST) }}"
      
